GET http://localhost:3000/api/companies
###

GET http://localhost:3000/api/company?id=2ac4ef6b-3ccd-4e1d-b321-58491e8aad


###
POST http://localhost:3000/api/company
Content-Type: application/json

{
 "name": "Escritório Corso",
 "cnpj": "11111111111"
}

###
PUT http://localhost:3000/api/company?id=abc
Content-Type: application/json

{
 "id": "0407e2ee-87e7-4260-adb0-8993d7269300",
 "name": "Escritório de Advocacia Justo",
 "cnpj": "12345678000200"
}

###
DELETE http://localhost:3000/api/company?id=68df5302-431c-4d80-a2ea-365e7cb29bfe
Content-Type: application/json

###
GET http://localhost:3000/api/clients
###

GET http://localhost:3000/api/client?document=09500099988


###
POST http://localhost:3000/api/client
Content-Type: application/json

{
 "document": "12312312312",
 "fistName": "Lucas",
 "lastName": "Mantes",
 "companyId": "0407e2ee-87e7-4260-adb0-8993d7269301"
}

###
PUT http://localhost:3000/api/client?document=09500099988
Content-Type: application/json

{
 "document": "09500099988",
 "fistName": "Fulano",
 "lastName": "Da Silva",
 "companyId": "0407e2ee-87e7-4260-adb0-8993d7269301"
}

###
DELETE http://localhost:3000/api/client?document=12312312312
Content-Type: application/json


###
GET http://localhost:3000/api/users
Content-Type: application/json

###
POST  http://localhost:3000/api/user
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "12345678",
  "firstName": "Fulano",
  "lastName": "da Silva",
  "companyId": "f663b25d-0d86-439d-a395-8586561312a4", 
  "role": "employee"  
}

###
POST  http://localhost:3000/login
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "12345678"
 
}
