version: "3.8"
services:
  backend:
    build:
      context: .
    container_name: backend
    ports:
      - "3000:3000"
    networks:
      - shared-network
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - shared-network

networks:
  shared-network:
