version: '3.8'
services:
    backend:
        build:
            context: .
        container_name: backend
        ports:
            - '3001:3001'
        networks:
            - shared-network
        depends_on:
            - db
    db:
        image: postgres:17
        container_name: db
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - '5432:5432'
        networks:
            - shared-network
        volumes:
            - postgres-data:/var/lib/postgresql/data

networks:
    shared-network:

volumes:
    postgres-data:
